# Gradle Properties
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Mod Properties
version = 0.1
maven_group = com.restonic4
archives_base_name = ambient

# Dependencies - check https://ornithemc.net/develop for the latest versions
minecraft_version = 1.0.0
loader_version = 0.19.5

feather_build = 1
raven_build = 1
sparrow_build = 1
nests_build = 15

osl_version = 0.20.3
